#!/usr/bin/env python

import sys

from rqt_svo.svo import Svo
from rqt_gui.main import Main

plugin = 'rqt_svo'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin)) # , plugin_argument_provider=Svo.add_arguments